// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fifaAdministration.Models;

namespace fifaAdministration.Migrations
{
    [DbContext(typeof(FifaDbContext))]
    [Migration("20191012075718_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("fifaAdministration.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AwayGoals");

                    b.Property<string>("AwayPlayer");

                    b.Property<int?>("GroupId");

                    b.Property<int>("HomeGoals");

                    b.Property<string>("HomePlayer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("fifaAdministration.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("fifaAdministration.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GroupId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("fifaAdministration.Models.Game", b =>
                {
                    b.HasOne("fifaAdministration.Models.Group", "Group")
                        .WithMany("Games")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("fifaAdministration.Models.Player", b =>
                {
                    b.HasOne("fifaAdministration.Models.Group", "Group")
                        .WithMany("Players")
                        .HasForeignKey("GroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
